stages:
  - test

# todo: builds caching
# check how other ppl struggle https://github.com/cypress-io/cypress-example-kitchensink/pull/106
# check some else https://docs.cypress.io/guides/continuous-integration/introduction#Caching
# https://docs.gitlab.com/ee/ci/caching/
Build & Test:
  image: cypress/browsers:node14.17.0-chrome91-ff89
  stage: test
  script:
    - yarn install --frozen-lockfile
    - npx cypress cache path
    - npx cypress cache list
    - npx cypress verify
    - yarn run cypress:run:dev
  artifacts:
    when: always
    paths:
      - e2e/cypress/videos/**/*.mp4
      - e2e/cypress/screenshots/**/*.png
    expire_in: 1 day
