version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  test:
    jobs:
      - cypress/run:
          yarn: true
          executor: with-chrome
          browser: chrome
  schedule:
    triggers:
      - schedule:
          cron: "0 7,10,13,16,19,22 * * *"
          filters:
            branches:
              only:
                - circleci
    jobs:
      - cypress/run:
          yarn: true
          executor: with-chrome
          browser: chrome
